# Configuração de Conexão com MariaDB (com fallback para variáveis de ambiente)
spring.datasource.url=jdbc:mariadb://localhost:3306/portal_db
spring.datasource.username=root
spring.datasource.password=usuario123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Flyway Migration
spring.flyway.enabled=true

# Habilitação das Virtual Threads do Java 21 (Alta performance de concorrência)
spring.threads.virtual.enabled=true

spring.mvc.problemdetails.enabled=true