name: CI/CD Pipeline - bit Solucoes

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Adicionamos o serviço do MariaDB para o GitHub Actions usar durante os testes
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: portal_db
          MYSQL_ROOT_PASSWORD: usuario123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Executar Testes com Maven
        run: ./mvnw verify
        env:
          DB_URL: jdbc:mariadb://localhost:3306/portal_db
          DB_USER: root
          DB_PASSWORD: usuario123